# Project information
site_name: MiguelNdeCarvalho's Docs
site_url: https://docs.miguelndecarvalho.pt
site_author: MiguelNdeCarvalho
site_description: >-
  Where the documentation of all of my projects is.
repo_name: MiguelNdeCarvalho
repo_url: https://github.com/MiguelNdeCarvalho/
edit_uri: ""
copyright: Copyright &copy; 2021 MiguelNdeCarvalho

# Material Theme
theme:
  name: material
  search_index_only: true
  palette:
    scheme: slate
    primary: teal
    accent: teal
  font:
    text: Exo 2
    code: JetBrains Mono
  feautures:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  plugins:
    - search:
      lang: en
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/solid/portrait
      link: https://www.miguelndecarvalho.pt
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/MiguelNdeCarvalho
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguelndecarvalho/
    - icon: fontawesome/brands/github
      link: https://twitter.com/squidfunk

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences